"""empty message

Revision ID: 5d61617ec7e7
Revises: 
Create Date: 2024-05-21 13:03:07.005659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d61617ec7e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers_info', schema=None) as batch_op:
        batch_op.drop_constraint('subscribers_info_ibfk_3', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers_info', schema=None) as batch_op:
        batch_op.create_foreign_key('subscribers_info_ibfk_3', 'user_info', ['subscriber_mobile_no'], ['mobile_no'])

    # ### end Alembic commands ###
